products:
  gcp_pubsub_handler:
    build:
      main-pkg: 'cmd/sensu_gcp_pubsub_handler'
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: darwin
                arch: amd64
              - os: linux
                arch: amd64